#!/bin/bash

# Help function
help () {
	echo "This is a script for playing youtube videos using mpv

	It's options are:
	-quality
	Selects the quality.
	Can be: audio, 144, 240, 360, 480, 720, 1080

	-d[evour]
	Uses the devour funtion

	-h
	Prints this help page.

	Also mpv an ytdl options are acceptable:

	-fs
	Fullscreen playback
	
	--start=<time>
	Seek to given (percent, seconds, or hh:mm:ss) position"
}

devour () {
	id=$(xdo id)
	xdo hide
	$("$@") > /dev/null 2>&1
	xdo show "$id"
}

#### Argument handling ####

if [ -z "$1" ]; then help && exit; fi

for arg in "$@" ; do
	case $arg in
		-audio)
			format="bestaudio/best"
			;;
		-144)
			format="bestvideo[height<=?144]+bestaudio/best"
			;;
		-240)
			format="bestvideo[height<=?240]+bestaudio/best"
			;;
		-360)
			format="bestvideo[height<=?360]+bestaudio/best"
			;;
		-480)
			format="bestvideo[height<=?480]+bestaudio/best"
			;;
		-720)
			format="bestvideo[height<=?720]+bestaudio/best"
			;;
		-1080)
			format="bestvideo[height<=?1080]+bestaudio/best"
			;;
		-d) # Use devour function
			command="devour"
			;;
		-h)
			help && exit
			;;
		*)
			argv="$argv $arg"
			;;
	esac
done

# Format defauts to 1080p
format=${format:-"bestvideo[height<=?1080]+bestaudio/best"}


$command mpv --ytdl-format="$format" $argv
